Repository pulumi/pulumi-azure, pull requests merged in 2019-05, with the labels that each got.

#227 Simplify http code
  sdk/nodejs/appservice/zMixins_http.ts
Labels: impact/no-changelog-required

#231 Upgrade to `@azure/functions` 1.0.3
  resources.go
  sdk/nodejs/package.json
Labels: impact/no-changelog-required

#249 Fix the build by fixing naming in cosmos example
  examples/cosmosdb/index.ts
Labels: impact/no-changelog-required

#251 Fix the build by fixing naming in cosmos example
  examples/cosmosdb/index.ts
Labels: impact/no-changelog-required

#254 Update pulumi-terraform
  go.mod
  go.sum
  sdk/go/azure/config/config.go
  sdk/nodejs/config/vars.ts
  sdk/nodejs/utilities.ts
  sdk/python/pulumi_azure/config/vars.py
  sdk/python/pulumi_azure/utilities.py
  sdk/python/setup.py
Labels: area/providers, impact/no-changelog-required

#262 Update to v1.29.0 of upstream
  CHANGELOG.md
  go.mod
  go.sum
  resources.go
  sdk/go/azure/appinsights/webTest.go
  sdk/go/azure/appservice/appService.go
  sdk/go/azure/containerservice/kubernetesCluster.go
  sdk/go/azure/eventhub/queue.go
  sdk/go/azure/network/applicationGateway.go
  sdk/go/azure/network/getVirtualNetwork.go
  sdk/nodejs/appinsights/index.ts
  sdk/nodejs/appinsights/webTest.ts
  sdk/nodejs/appservice/appService.ts
  sdk/nodejs/automation/schedule.ts
  sdk/nodejs/containerservice/getKubernetesServiceVersions.ts
  sdk/nodejs/containerservice/kubernetesCluster.ts
  sdk/nodejs/devspace/controller.ts
  sdk/nodejs/eventhub/queue.ts
  sdk/nodejs/network/applicationGateway.ts
  sdk/nodejs/network/getVirtualNetwork.ts
  sdk/nodejs/tsconfig.json
  sdk/python/pulumi_azure/appinsights/__init__.py
  sdk/python/pulumi_azure/appinsights/web_test.py
  sdk/python/pulumi_azure/appservice/app_service.py
  sdk/python/pulumi_azure/containerservice/kubernetes_cluster.py
  sdk/python/pulumi_azure/eventhub/queue.py
  sdk/python/pulumi_azure/network/application_gateway.py
  sdk/python/pulumi_azure/network/get_virtual_network.py
  sdk/python/pulumi_azure/tables.py
Labels: area/providers
