Repository pulumi/pulumi-azure, pull requests merged in 2019-07, with the labels that each got.

#305 Fix mismatch between two merged issues
  sdk/nodejs/appservice/zMixins.ts
  sdk/nodejs/eventhub/zMixins.ts
Labels: impact/no-changelog-required

#306 Update pulumi-terraform to 08d502e9b4
  go.mod
  go.sum
Labels: area/providers

#311 Update azure rest versions to avoid conflict
  resources.go
  sdk/nodejs/package.json
Labels: impact/no-changelog-required

#318 Introduce constants for AppService Plan Kinds
  CHANGELOG.md
  resources.go
  sdk/nodejs/appservice/index.ts
  sdk/nodejs/appservice/kind.ts
  sdk/nodejs/appservice/plan.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers, impact/usability, kind/enhancement
