Repository pulumi/pulumi-azure, pull requests merged in 2019-06, with the labels that each got.

#265 Switch upstream to terraform-providers/terraform-provider-azurerm
  Makefile
  cmd/pulumi-resource-azure/main.go
  go.mod
  go.sum
Labels: area/providers, impact/no-changelog-required

#267 Event Hub Trigger for IoT Hub
  CHANGELOG.md
  examples/examples_test.go
  examples/iot/Pulumi.yaml
  examples/iot/index.ts
  examples/iot/package.json
  examples/iot/tsconfig.json
  resources.go
  sdk/nodejs/eventhub/zMixins.ts
  sdk/nodejs/iot/index.ts
  sdk/nodejs/iot/zMixins.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers, kind/enhancement

#272 Update to v1.30.0 of upstream
  CHANGELOG.md
  go.mod
  go.sum
  resources.go
  sdk/go/azure/appservice/appService.go
  sdk/go/azure/appservice/getAppServicePlan.go
  sdk/go/azure/appservice/plan.go
  sdk/go/azure/compute/managedDisk.go
  sdk/go/azure/network/getGatewayConnection.go
  sdk/go/azure/redis/getCache.go
  sdk/go/azure/role/assignment.go
  sdk/go/azure/sql/database.go
  sdk/go/azure/sql/getServer.go
  sdk/nodejs/apimanagement/service.ts
  sdk/nodejs/appservice/appService.ts
  sdk/nodejs/appservice/getAppService.ts
  sdk/nodejs/appservice/getAppServicePlan.ts
  sdk/nodejs/appservice/plan.ts
  sdk/nodejs/appservice/slot.ts
  sdk/nodejs/compute/managedDisk.ts
  sdk/nodejs/network/getGatewayConnection.ts
  sdk/nodejs/network/index.ts
  sdk/nodejs/redis/getCache.ts
  sdk/nodejs/redis/index.ts
  sdk/nodejs/role/assignment.ts
  sdk/nodejs/sql/database.ts
  sdk/nodejs/sql/getServer.ts
  sdk/nodejs/sql/index.ts
  sdk/nodejs/tsconfig.json
  sdk/python/pulumi_azure/appservice/app_service.py
  sdk/python/pulumi_azure/appservice/get_app_service_plan.py
  sdk/python/pulumi_azure/appservice/plan.py
  sdk/python/pulumi_azure/compute/managed_disk.py
  sdk/python/pulumi_azure/network/__init__.py
  sdk/python/pulumi_azure/network/get_gateway_connection.py
  sdk/python/pulumi_azure/redis/__init__.py
  sdk/python/pulumi_azure/redis/get_cache.py
  sdk/python/pulumi_azure/role/assignment.py
  sdk/python/pulumi_azure/sql/__init__.py
  sdk/python/pulumi_azure/sql/database.py
  sdk/python/pulumi_azure/sql/get_server.py
  sdk/python/pulumi_azure/tables.py
Labels: area/providers

#274 Upgrade to v1.30.1 of Azurerm provider
  CHANGELOG.md
  go.mod
  go.sum
Labels: area/providers

#276 Adding a mixin for Azure Locations
  CHANGELOG.md
  examples/webserver/index.ts
  resources.go
  sdk/nodejs/index.ts
  sdk/nodejs/location.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers, impact/usability, kind/enhancement

#280 Export Locations module for correct Location namespacing
  examples/webserver/index.ts
  sdk/nodejs/location.ts
Labels: impact/no-changelog-required, impact/usability

#284 Add the UAE Azure regions that were opened
  sdk/nodejs/location.ts
Labels: impact/no-changelog-required, kind/enhancement

#287 Update pulumi-terraform to 3635bed3a5
  go.mod
  go.sum
Labels: area/providers

#292 Update .travis.yml to scripts
  .travis.yml
Labels: area/providers, impact/no-changelog-required
