Repository pulumi/pulumi-azure, pull requests merged in 2019-08, with the labels that each got.

#324 Update docs
  go.mod
  go.sum
  resources.go
  sdk/go/azure/core/templateDeployment.go
  sdk/go/azure/network/networkSecurityGroup.go
  sdk/go/azure/network/networkSecurityRule.go
  sdk/go/azure/network/route.go
  sdk/go/azure/network/subnet.go
  sdk/go/azure/network/virtualNetwork.go
  sdk/go/azure/storage/getAccountSAS.go
  sdk/nodejs/apimanagement/api.ts
  sdk/nodejs/apimanagement/certificate.ts
  sdk/nodejs/apimanagement/logger.ts
  sdk/nodejs/apimanagement/openIdConnectProvider.ts
  sdk/nodejs/apimanagement/product.ts
  sdk/nodejs/apimanagement/service.ts
  sdk/nodejs/apimanagement/user.ts
  sdk/nodejs/automation/stringVariable.ts
  sdk/nodejs/batch/certificate.ts
  sdk/nodejs/compute/scaleSet.ts
  sdk/nodejs/core/templateDeployment.ts
  sdk/nodejs/dns/caaRecord.ts
  sdk/nodejs/eventhub/namespace.ts
  sdk/nodejs/eventhub/namespaceAuthorizationRule.ts
  sdk/nodejs/eventhub/queue.ts
  sdk/nodejs/eventhub/queueAuthorizationRule.ts
  sdk/nodejs/eventhub/subscription.ts
  sdk/nodejs/eventhub/subscriptionRule.ts
  sdk/nodejs/eventhub/topic.ts
  sdk/nodejs/eventhub/topicAuthorizationRule.ts
  sdk/nodejs/iot/consumerGroup.ts
  sdk/nodejs/monitoring/activityLogAlert.ts
  sdk/nodejs/monitoring/getActionGroup.ts
  sdk/nodejs/network/connectionMonitor.ts
  sdk/nodejs/network/networkConnectionMonitor.ts
  sdk/nodejs/network/networkSecurityGroup.ts
  sdk/nodejs/network/networkSecurityRule.ts
  sdk/nodejs/network/route.ts
  sdk/nodejs/network/subnet.ts
  sdk/nodejs/network/virtualNetwork.ts
  sdk/nodejs/package.json
  sdk/nodejs/relay/namespace.ts
  sdk/nodejs/role/definition.ts
  sdk/nodejs/signalr/service.ts
  sdk/nodejs/storage/getAccountSAS.ts
  sdk/nodejs/trafficmanager/endpoint.ts
  sdk/python/pulumi_azure/core/template_deployment.py
  sdk/python/pulumi_azure/network/network_security_group.py
  sdk/python/pulumi_azure/network/network_security_rule.py
  sdk/python/pulumi_azure/network/route.py
  sdk/python/pulumi_azure/network/subnet.py
  sdk/python/pulumi_azure/network/virtual_network.py
Labels: impact/no-changelog-required

#325 Remove explicit location assignments from examples
  examples/aci-multi/index.ts
  examples/aci-volume-mount/index.ts
  examples/aks/index.ts
  examples/blob/index.ts
  examples/cosmosdb/index.ts
  examples/eventgrid/index.ts
  examples/eventhub/index.ts
  examples/examples_test.go
  examples/http-external/index.ts
  examples/http-multi/index.ts
  examples/http/index.ts
  examples/iot/index.ts
  examples/loadbalancer/index.ts
  examples/multi-callback-all/index.ts
  examples/queue/index.ts
  examples/table/index.ts
  examples/timer/index.ts
  examples/topic/index.ts
  examples/webserver/index.ts
Labels: impact/no-changelog-required

#326 Fix issues and warning in the LB example
  examples/loadbalancer/index.ts
Labels: impact/no-changelog-required

#328 Fix location propagation of callback functions
  CHANGELOG.md
  sdk/nodejs/appservice/zMixins.ts
Labels: area/providers, kind/bug

#329 Adding examples that test a python resource and a datasource
  examples/datasource-py/.gitignore
  examples/datasource-py/Pulumi.yaml
  examples/datasource-py/README.md
  examples/datasource-py/__main__.py
  examples/datasource-py/requirements.txt
  examples/eventhub-py/.gitignore
  examples/eventhub-py/Pulumi.yaml
  examples/eventhub-py/README.md
  examples/eventhub-py/__main__.py
  examples/eventhub-py/requirements.txt
  examples/examples_test.go
  examples/minimal-py/.gitignore
  examples/minimal-py/Pulumi.yaml
  examples/minimal-py/__main__.py
  examples/minimal-py/requirements.txt
Labels: impact/no-changelog-required

#336 Fix the Service Bus migration example
  examples/servicebus-migration-test/Pulumi.yaml
  examples/servicebus-migration-test/index.ts
  examples/servicebus-migration-test/step2/index.ts
Labels: impact/no-changelog-required

#338 Remove the mix of subnets from webserver to avoid refresh issues
  examples/examples_test.go
  examples/webserver/index.ts
Labels: impact/no-changelog-required

#335 Add the work to allow tests to run upgrades of providers
  examples/aci-multi/package.json
  examples/aci-volume-mount/package.json
  examples/blob/package.json
  examples/cosmosdb/package.json
  examples/datasource-py/requirements.txt
  examples/eventgrid/index.ts
  examples/eventgrid/package.json
  examples/eventhub-py/requirements.txt
  examples/eventhub/package.json
  examples/examples_test.go
  examples/http-external/package.json
  examples/http-multi/package.json
  examples/http/package.json
  examples/iot/package.json
  examples/loadbalancer/package.json
  examples/minimal-py/requirements.txt
  examples/msi-renamed-to-authorization/package.json
  examples/multi-callback-all/package.json
  examples/queue/package.json
  examples/servicebus-migration-test/package.json
  examples/table/package.json
  examples/timer/package.json
  examples/topic/package.json
  examples/webserver/package.json
  go.mod
  go.sum
Labels: impact/no-changelog-required

#339 Fix subnet inconsistency in the LB sample
  examples/loadbalancer/index.ts
Labels: impact/no-changelog-required

#342 Add the Get Started button and prompt
  README.md
Labels: area/providers, impact/no-changelog-required
